Benjamin/controller
180D-FW-2020/Team3 pull request #15
Opened 2020-11-12 08:35 UTC by benjaminruiz99

### Summary
These files will be the base for using the BerryIMU as a "steering wheel". For our purposes, our axis of rotation will be the x-axis. The script also calibrates the steady state of the steering wheel at start, and whenever the pull-up button connected to the IO pin is pressed.

### Test plan
- The main_module python script successfully recognizes when the IMU is being tilted, and in which direction along the x-axis. 
- The main_module script is also capable of successfully recalibrating the steady state (position of going straight) of the steering wheel.

### Future plan
Implement MQTT communications so that a script running on a computer can read messages about the state of the angle of the wheel from the Raspberry Pi connected to the IMU.

2020-11-19 18:05 UTC, abdullahelqaq requested changes
Looks good, but I think it'd be best if we run the IMU code in a background thread. This should help clear up `main_module.py` too, where we should keep as little actual implementation as possible. Here's the file structure change I'm suggesting:

1. Move `IMU.py`, `LIS3MDL.py`, and `LSM6DSL.py` to a subdirectory called `BerryIMU`
2. Change what you currently have as `main_module.py` to `compute_angle.py`. You'll also have to change the import in this file on line 13 to `import BerryIMU.IMU`.

This should leave you with something like this:
```
wheel
|__compute_angle.py
|__BerryIMU
    |__IMU.py
    |__LIS3MDL.py
    |__LSM6DSL.py
```

That way, I can simply call your code on a thread from my working implementation of the controller main module.

2020-11-19 18:05 UTC, abdullahelqaq commented on controller/wheel/calibrateBerryIMU.py
> +#   The BerryIMUv1, BerryIMUv2 and BerryIMUv3 are supported
I don't think we need to include this file in this PR

2020-11-20 00:26 UTC, abdullahelqaq approved these changes

2020-11-20 01:20 UTC, therealhuy approved these changes

2020-11-20 01:32 UTC, merged